/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demos_ndk_FeatureDetect */

#ifndef _Included_com_demos_ndk_FeatureDetect
#define _Included_com_demos_ndk_FeatureDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demos_ndk_FeatureDetect
 * Method:    nativeMarkImage
 * Signature: ([III[III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_demos_ndk_FeatureDetect_nativeMarkImage
  (JNIEnv *, jobject, jintArray, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
